import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Link,Navigate,Route,Routes,useLocation} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import './index.css';
import {Landing} from './components/brand';
import {Button} from './components/ui';
import {ArrowLeft,CheckCircle2} from 'lucide-react';
function PendingApproval({user}:{user:User|null}){
  // Never show the generic pending card for an account that has not completed onboarding.
  // This makes the trainee profile form the authoritative next step after signup.
  if(user?.role==='trainee'&&!user.onboardingComplete)return <Navigate to="/trainee/onboarding" replace/>;
  if(user?.role==='trainer'&&!user.onboardingComplete)return <Navigate to="/trainer/onboarding" replace/>;
  const trainer=user?.role==='trainer';
  return <div className="grid min-h-screen place-items-center bg-canvas p-6"><div className="w-full max-w-lg rounded-3xl border border-line bg-white p-8 text-center shadow-soft"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-teal-50 text-growth"><CheckCircle2 size={26}/></div><p className="eyebrow mt-5">{trainer?'Trainer approval requested':'Trainee application submitted'}</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight">{trainer?'Your trainer profile is under review.':'Your trainee profile is under review.'}</h1><p className="mt-3 text-sm leading-6 text-muted">{trainer?'Your teaching profile and professional credentials were submitted successfully. An administrator will review them before trainer access is enabled.':'Your professional profile was submitted successfully. An administrator will review it before trainee access is enabled.'}</p><div className="mt-6 rounded-2xl border border-teal-100 bg-teal-50/70 p-4 text-left"><p className="text-sm font-semibold text-growth">Administrator review</p><p className="mt-1 text-xs leading-5 text-muted">{trainer?'The administrator will verify your teaching role, qualification, experience and expertise. After approval, sign in to open your trainer dashboard.':'After approval, sign in again. Your role-based diagnostic assessment will then become available.'}</p></div><Link to="/" className="mt-6 inline-flex"><Button>Back to Home <ArrowLeft size={15}/></Button></Link></div></div>}
import {SignIn,SignUp} from './pages/Auth';
import {AppShell} from './layouts/AppShell';
import {AdminDashboard,Loading,TraineeDashboard,TrainerDashboard} from './pages/Dashboards';
import {AdminAnalytics,AdminAnnouncements,AdminAssessments,AdminCapacity,AdminCertificates,AdminCourses,AdminRoles,AdminUsers,AdminApprovals,AdminProfile,Assessments,Certificates,CourseDetail,Diagnostic,Feedback,Gaps,LearnerDetail,Learning,Notifications,Onboarding,Profile,Reassessment,Resources,SettingsPage,Skills,Roadmap,ExploreCourses,TraineeInterventions,TrainerAssessments,TrainerAssessmentCreate,TrainerCourseCreate,TrainerCourses,TrainerLearners,TrainerProfile,TrainerFeedback,TrainerSupport,Trainers,Verify,TrainerOnboarding} from './pages/FeaturePages';
import {api,get} from './lib/api';
import {User} from './lib/types';

class AppErrorBoundary extends React.Component<{children:React.ReactNode},{hasError:boolean}>{state={hasError:false};static getDerivedStateFromError(){return {hasError:true}};componentDidCatch(error:unknown){console.error(error)};render(){if(this.state.hasError)return <div className="grid min-h-screen place-items-center bg-canvas p-6"><div className="surface max-w-md p-8 text-center shadow-soft"><div className="mx-auto h-12 w-12 rounded-2xl bg-red-50"/><h1 className="mt-5 font-display text-2xl font-bold">Something went wrong</h1><p className="mt-2 text-sm leading-6 text-muted">The page could not be displayed. Refresh and try again.</p><button className="mt-5 rounded-xl bg-brand px-4 py-2.5 text-sm font-semibold text-white" onClick={()=>window.location.reload()}>Try Again</button></div></div>;return this.props.children}}

const qc=new QueryClient({defaultOptions:{queries:{retry:1,staleTime:30_000,refetchOnWindowFocus:false}}});

function StartupLoader(){return <div className="cc-startup-loader" role="status" aria-label="Loading Capacity Connect"><div className="cc-loader-mark"><span className="cc-loader-core"/><span className="cc-loader-orbit cc-orbit-a"/><span className="cc-loader-orbit cc-orbit-b"/><span className="cc-loader-node cc-node-a"/><span className="cc-loader-node cc-node-b"/><span className="cc-loader-node cc-node-c"/></div><p className="mt-6 font-display text-xl font-bold tracking-tight">Capacity Connect</p><p className="mt-1 text-sm text-muted">Connecting skills to growth</p></div>}
function App(){const [user,setUser]=useState<User|null>(null);const [checking,setChecking]=useState(true);const [minimumLoader,setMinimumLoader]=useState(true);useEffect(()=>{const token=localStorage.getItem('cc_token');const timer=window.setTimeout(()=>setMinimumLoader(false),850);if(!token){setChecking(false);return ()=>window.clearTimeout(timer)}get<{user:User}>('/auth/me').then(d=>setUser(d.user)).catch(()=>{localStorage.removeItem('cc_token');localStorage.removeItem('cc_user')}).finally(()=>setChecking(false));return ()=>window.clearTimeout(timer)},[]);if(checking||minimumLoader)return <StartupLoader/>;
 const protectedRoute=(role:User['role'],element:React.ReactNode,shell=true)=><Guard user={user} role={role} shell={shell}>{element}</Guard>;
 return <Routes>
  <Route path="/" element={<Landing/>}/><Route path="/pending-approval" element={<PendingApproval user={user}/>}/><Route path="/trainer/onboarding" element={user&&user.role==='trainer'?<OnboardingOnly><TrainerOnboarding/></OnboardingOnly>:<Navigate to="/signin" replace/>}/><Route path="/signin" element={<SignIn onLogin={setUser}/>}/><Route path="/signup" element={<SignUp onLogin={setUser}/>}/><Route path="/verify/:id" element={<Verify/>}/>
  <Route path="/trainee/dashboard" element={protectedRoute('trainee',<TraineeDashboard/>)}/><Route path="/trainee/diagnostic" element={protectedRoute('trainee',<Diagnostic/>,false)}/><Route path="/trainee/reassessment" element={protectedRoute('trainee',<Reassessment/>)}/><Route path="/trainee/feedback" element={protectedRoute('trainee',<Feedback/>)}/><Route path="/trainee/notifications" element={protectedRoute('trainee',<Notifications/>)}/><Route path="/trainee/settings" element={protectedRoute('trainee',<SettingsPage/>)}/><Route path="/trainee/onboarding" element={user&&user.role==='trainee'?<OnboardingOnly><Onboarding/></OnboardingOnly>:<Navigate to="/signin" replace/>}/><Route path="/trainee/profile" element={protectedRoute('trainee',<Profile/>)}/><Route path="/trainee/skills" element={protectedRoute('trainee',<Skills/>)}/><Route path="/trainee/gaps" element={protectedRoute('trainee',<Gaps/>)}/><Route path="/trainee/learning" element={protectedRoute('trainee',<Learning/>)}/><Route path="/trainee/courses" element={protectedRoute('trainee',<ExploreCourses/>)}/><Route path="/trainee/assessments" element={protectedRoute('trainee',<Assessments/>)}/><Route path="/trainee/trainers" element={protectedRoute('trainee',<Trainers/>)}/><Route path="/trainee/certificates" element={protectedRoute('trainee',<Certificates/>)}/><Route path="/trainee/interventions" element={protectedRoute('trainee',<TraineeInterventions/>)}/><Route path="/trainee/roadmap" element={protectedRoute('trainee',<Roadmap/>)}/>
  <Route path="/courses/:id" element={protectedRoute('trainee',<CourseDetail/>)}/>
  <Route path="/trainer/notifications" element={protectedRoute('trainer',<Notifications/>)}/><Route path="/trainer/settings" element={protectedRoute('trainer',<SettingsPage/>)}/><Route path="/trainer/dashboard" element={protectedRoute('trainer',<TrainerDashboard/>)}/><Route path="/trainer/profile" element={protectedRoute('trainer',<TrainerProfile/>)}/><Route path="/trainer/learners" element={protectedRoute('trainer',<TrainerLearners/>)}/><Route path="/trainer/learners/:id" element={protectedRoute('trainer',<LearnerDetail/>)}/><Route path="/trainer/courses" element={protectedRoute('trainer',<TrainerCourses/>)}/><Route path="/trainer/courses/new" element={protectedRoute('trainer',<TrainerCourseCreate/>)}/><Route path="/trainer/resources" element={protectedRoute('trainer',<Resources/>)}/><Route path="/trainer/resources/new" element={protectedRoute('trainer',<Resources/>)}/><Route path="/trainer/assessments" element={protectedRoute('trainer',<TrainerAssessments/>)}/><Route path="/trainer/assessments/new" element={protectedRoute('trainer',<TrainerAssessmentCreate/>)}/><Route path="/trainer/support" element={protectedRoute('trainer',<TrainerSupport/>)}/><Route path="/trainer/feedback" element={protectedRoute('trainer',<TrainerFeedback/>)}/>
  <Route path="/admin/notifications" element={protectedRoute('admin',<Notifications/>)}/><Route path="/admin/settings" element={protectedRoute('admin',<SettingsPage/>)}/><Route path="/admin/dashboard" element={protectedRoute('admin',<AdminDashboard/>)}/><Route path="/admin/profile" element={protectedRoute('admin',<AdminProfile/>)}/><Route path="/admin/users" element={protectedRoute('admin',<AdminUsers/>)}/><Route path="/admin/roles" element={protectedRoute('admin',<AdminRoles/>)}/><Route path="/admin/competencies" element={<Navigate to="/admin/roles" replace/>}/><Route path="/admin/courses" element={protectedRoute('admin',<AdminCourses/>)}/><Route path="/admin/assessments" element={protectedRoute('admin',<AdminAssessments/>)}/><Route path="/admin/certificates" element={protectedRoute('admin',<AdminCertificates/>)}/><Route path="/admin/announcements" element={protectedRoute('admin',<AdminAnnouncements/>)}/><Route path="/admin/analytics" element={protectedRoute('admin',<AdminAnalytics/>)}/><Route path="/admin/capacity" element={protectedRoute('admin',<AdminCapacity/>)}/><Route path="/admin/trainers" element={<Navigate to="/admin/capacity" replace/>}/><Route path="/admin/approvals" element={protectedRoute('admin',<AdminApprovals/>)}/>
  <Route path="*" element={<Navigate to="/" replace/>}/>
 </Routes>;
}
function OnboardingOnly({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-canvas">{children}</div>}
function Guard({user,role,children,shell=true}:{user:User|null;role:User['role'];children:React.ReactNode;shell?:boolean}){const loc=useLocation();if(!user)return <Navigate to={`/signin?next=${encodeURIComponent(loc.pathname)}`} replace/>;if(user.role!==role)return <Navigate to={`/${user.role}/dashboard`} replace/>;
  if(role==='trainee'){
    // Onboarding always wins over approval state. A freshly created trainee must see the form.
    if(!user.onboardingComplete&&loc.pathname!=='/trainee/onboarding')return <Navigate to="/trainee/onboarding" replace/>;
    if((user.status==='pending'||user.approvalRequired)&&loc.pathname!=='/trainee/onboarding')return <Navigate to="/pending-approval" replace/>;
    const diagnosticDone=user.diagnosticTestStatus==='completed'||user.diagnosticComplete;
    if(!diagnosticDone&&loc.pathname!=='/trainee/diagnostic'&&user.status==='active')return <Navigate to="/trainee/diagnostic" replace/>;
    if(diagnosticDone&&loc.pathname==='/trainee/diagnostic')return <Navigate to="/trainee/dashboard" replace/>;
  }
  if(role==='trainer'){
    if(!user.onboardingComplete&&loc.pathname!=='/trainer/onboarding')return <Navigate to="/trainer/onboarding" replace/>;
    if((user.status==='pending'||user.approvalRequired)&&loc.pathname!=='/trainer/onboarding')return <Navigate to="/pending-approval" replace/>;
  }
  return shell?<AppShell user={user}>{children}</AppShell>:<div className="min-h-screen bg-canvas">{children}</div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><AppErrorBoundary><QueryClientProvider client={qc}><BrowserRouter><App/></BrowserRouter></QueryClientProvider></AppErrorBoundary></React.StrictMode>);
