import {useState} from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,LockKeyhole,Network,ShieldCheck,Users,BookOpen} from 'lucide-react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {Button,Card,Field,TextareaField,Toast} from '../components/ui';
import {Logo} from '../components/brand';
import {api} from '../lib/api';

export function SignIn({onLogin}:{onLogin:(u:any)=>void}){const [email,setEmail]=useState('ananya@imd.gov.in'),[password,setPassword]=useState('Demo@123'),[err,setErr]=useState(''),[loading,setLoading]=useState(false);const nav=useNavigate();const submit=async(e:any)=>{e.preventDefault();setLoading(true);setErr('');try{const r=await api.post('/auth/signin',{email,password});localStorage.setItem('cc_token',r.data.data.token);localStorage.setItem('cc_user',r.data.data.user.id);onLogin(r.data.data.user);const u=r.data.data.user;const destination=u.role==='trainee'&&u.diagnosticTestStatus!=='completed'?'/trainee/diagnostic':`/${u.role}/dashboard`;nav(destination)}catch(e:any){setErr(e.response?.data?.error?.message||'Something went wrong. Please try again.')}finally{setLoading(false)}};return <AuthFrame><div className="w-full max-w-md"><BackHome/><Card className="p-7 sm:p-8"><Logo/><h1 className="mt-8 font-display text-3xl font-bold">Welcome back</h1><p className="mt-2 text-sm leading-6 text-muted">Sign in to continue your learning journey.</p><form onSubmit={submit} className="mt-7 space-y-4"><Field label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><Field label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/>{err&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-700">{err}</div>}<Button className="w-full" loading={loading} type="submit">Sign In <ArrowRight size={16}/></Button></form><div className="mt-6 grid gap-2 rounded-2xl bg-slate-50 p-4 text-xs leading-5 text-muted"><p className="font-semibold text-ink">Demo accounts</p><p><b>Trainee:</b> ananya@imd.gov.in / Demo@123</p><p><b>Trainer:</b> rao@imd.gov.in / Demo@123</p><p><b>Admin:</b> admin@imd.gov.in / Demo@123</p></div><p className="mt-6 text-center text-sm text-muted">New to Capacity Connect? <Link className="font-bold text-brand" to="/signup">Create account</Link></p></Card></div></AuthFrame>}

export function SignUp({onLogin}:{onLogin:(u:any)=>void}){
  const [params]=useSearchParams();
  const [role,setRole]=useState<'trainee'|'trainer'>(params.get('role')==='trainer'?'trainer':'trainee');
  const [step,setStep]=useState(1);
  const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[err,setErr]=useState(''),[loading,setLoading]=useState(false);
  const nav=useNavigate();
  const submitAccount=async(e:any)=>{
    e.preventDefault();setErr('');
    if(password!==confirm){setErr('Passwords do not match.');return}
    setLoading(true);
    try{
      const r=await api.post('/auth/signup',{name,email,password,role});
      localStorage.setItem('cc_token',r.data.data.token);localStorage.setItem('cc_user',r.data.data.user.id);onLogin(r.data.data.user);
      // A new account must always enter its role-specific profile form first.
      nav(r.data.data.user.role==='trainer'?'/trainer/onboarding':'/trainee/onboarding',{replace:true});
    }catch(e:any){setErr(e.response?.data?.error?.message||'Could not create your account.')}finally{setLoading(false)}
  };
  return <AuthFrame><div className="w-full max-w-2xl"><BackHome/><Card className="p-7 sm:p-8"><Logo/>
    <div className="mt-8 flex items-center justify-between gap-4"><div><p className="eyebrow">Create account</p><h1 className="mt-2 font-display text-3xl font-bold">Start with your account.</h1><p className="mt-2 text-sm leading-6 text-muted">Enter your basic details first. We will collect your professional profile on the next screen.</p></div><div className="hidden shrink-0 sm:grid h-11 w-11 place-items-center rounded-2xl bg-indigo-50 font-mono text-sm font-bold text-brand">1/2</div></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2">{[['trainee','Trainee','Build a learner profile and take a diagnostic after approval.',Users],['trainer','Trainer','Share your teaching expertise and request administrator approval.',BookOpen]].map(([r,t,d,I]:any)=><button key={r} type="button" onClick={()=>setRole(r)} className={`focus-ring rounded-2xl border p-5 text-left transition ${role===r?'border-brand bg-indigo-50 shadow-sm':'border-line bg-white hover:border-slate-300'}`}><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white text-brand shadow-sm"><I size={18}/></div><span className="font-display font-bold">{t}</span></div>{role===r&&<CheckCircle2 className="text-brand" size={19}/>}</div><p className="mt-3 text-sm leading-6 text-muted">{d}</p></button>)}</div>
    {step===1&&<form onSubmit={submitAccount} className="mt-7 space-y-4"><Field label="Full name" value={name} onChange={e=>setName(e.target.value)} required autoComplete="name"/><Field label="Work email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/><div className="grid gap-4 sm:grid-cols-2"><Field label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="new-password"/><Field label="Confirm password" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required autoComplete="new-password"/></div><label className="flex items-start gap-3 text-xs leading-5 text-muted"><input type="checkbox" required className="mt-1 accent-indigo-600"/>I agree to use Capacity Connect for professional learning and organizational capacity building.</label>{err&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-700">{err}</div>}<Button className="w-full" loading={loading} type="submit">Continue to Profile <ArrowRight size={16}/></Button></form>}
    <p className="mt-6 text-center text-sm text-muted">Already have an account? <Link className="font-bold text-brand" to="/signin">Sign in</Link></p>
  </Card></div></AuthFrame>
}
function BackHome(){return <Link to="/" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-muted hover:text-ink"><ArrowLeft size={15}/> Back to home</Link>}
function AuthFrame({children}:{children:any}){return <div className="min-h-screen bg-canvas lg:grid lg:grid-cols-2"><div className="hidden min-h-screen bg-deep p-10 text-white lg:flex lg:flex-col lg:justify-between xl:p-14"><Logo light/><div><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-200">CAPACITY CONNECT</p><h2 className="mt-5 max-w-xl font-display text-5xl font-bold leading-[1.08] tracking-tight">From skill gaps to measurable growth.</h2><p className="mt-5 max-w-md text-sm leading-7 text-indigo-100">A competency-first learning experience designed to turn organizational needs into measurable capability.</p><div className="mt-10 space-y-4 text-sm text-indigo-100"><div className="flex gap-3"><ShieldCheck size={18}/>Explainable competency scoring</div><div className="flex gap-3"><LockKeyhole size={18}/>Role-aware access</div><div className="flex gap-3"><Network size={18}/>Learning connected to organizational need</div></div></div><p className="text-xs text-indigo-200">Build Skills. Measure Competency. Strengthen Capacity.</p></div><div className="flex min-h-screen items-center justify-center p-4 sm:p-8">{children}</div></div>}
