import { Router, Response } from 'express';
import { z } from 'zod';
import { announcements, assessmentAttempts, certificates, competencies, courses, enrollments, feedback, interventions, learners, notifications, organization, resources, roleRequirements, skillGaps, trainerAssessments, trainerMatches, traineeProgress, users, diagnosticQuestionBank, traineeProfiles, trainingRequests, trainerProfiles } from '../data.js';
import { auth, issueToken, publicUser, role, AuthedRequest } from '../middleware/auth.js';
import { certificateEligible, competency, gap, priority, trainerMatch } from '../services/engine.js';

const r=Router();
const ok=(res:Response,data:unknown)=>res.json({success:true,data});
const fail=(res:Response,status:number,code:string,message:string)=>res.status(status).json({success:false,error:{code,message}});
const userSchema=z.object({name:z.string().trim().min(2).max(80),email:z.string().trim().email().max(160),password:z.string().min(8).max(100),role:z.enum(['trainee','trainer']),jobRole:z.string().trim().min(2).max(100).optional(),department:z.string().trim().min(2).max(120).optional(),qualification:z.string().max(160).optional(),experience:z.string().max(160).optional(),skills:z.string().max(1000).optional(),interests:z.string().max(1000).optional(),certificates:z.string().max(1000).optional(),organization:z.string().max(160).optional()});

r.get('/health',(_,res)=>ok(res,{status:'ok',service:'capacity-connect-api',version:'v1',organization:organization.name}));

r.post('/auth/signin',(req,res)=>{
  const p=z.object({email:z.string().email(),password:z.string().min(1)}).safeParse(req.body);
  if(!p.success)return fail(res,400,'VALIDATION_ERROR','Enter a valid email and password.');
  const u=users.find(x=>x.email.toLowerCase()===p.data.email.toLowerCase()&&x.password===p.data.password);
  if(!u)return fail(res,401,'AUTH_INVALID_CREDENTIALS','The email or password is incorrect.');
  if(u.status==='pending')return fail(res,403,'AUTH_ACCOUNT_PENDING','Your account is waiting for administrator approval.');
  if(u.status==='rejected')return fail(res,403,'AUTH_ACCOUNT_REJECTED','Your account was not approved. Please contact your administrator.');
  const token=issueToken(u); ok(res,{user:publicUser(u),token});
});

r.post('/auth/signup',(req,res)=>{
  const p=userSchema.safeParse(req.body);
  if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please check your account details.');
  if(users.some(u=>u.email.toLowerCase()===p.data.email.toLowerCase()))return fail(res,409,'DUPLICATE_ACCOUNT','An account with this email already exists.');
  const id=`u${Date.now()}`;
  const isTrainee=p.data.role==='trainee';
  const status='pending';
  const u:any={id,name:p.data.name,email:p.data.email,password:p.data.password,role:p.data.role,status,organizationId:organization.id,department:p.data.department||'Not set',jobRole:p.data.jobRole||(isTrainee?'Trainee':'Trainer'),onboardingComplete:false,approvalRequired:true};
  if(isTrainee){u.diagnosticComplete=false;u.diagnosticTestStatus='not_started';}
  users.push(u);
  if(isTrainee){
    traineeProfiles[u.id]={qualification:'',experience:'',skills:[],interests:[],certificates:[],organization:organization.name};
    const token=issueToken(u);
    ok(res,{message:'Account created. Complete your trainee profile, then request administrator approval.',user:publicUser(u),status:'pending',diagnosticTestStatus:'not_started',token});
    return;
  }
  const token=issueToken(u);
  ok(res,{message:'Account created. Continue to trainer onboarding.',user:publicUser(u),token});
});
r.post('/auth/signout',auth,(_,res)=>ok(res,{signedOut:true}));
r.get('/search',auth,(req:AuthedRequest,res)=>{const q=String(req.query.q||'').trim().toLowerCase();if(q.length<2)return ok(res,{results:[]});const out:{label:string;path:string}[]=[];const add=(label:string,path:string)=>{if(!out.some(x=>x.path===path))out.push({label,path})};if(req.user!.role==='trainer'){learners.filter(l=>[l.name,l.skill,l.status].some(v=>String(v).toLowerCase().includes(q))).slice(0,4).forEach(l=>add(`${l.name} · ${l.skill}`,`/trainer/learners/${l.id}`));courses.filter(c=>c.trainerId===req.user!.id&&[c.title,c.description,c.status].some(v=>String(v).toLowerCase().includes(q))).slice(0,3).forEach(c=>add(c.title,'/trainer/courses'));resources.filter(r=>r.ownerId===req.user!.id&&[r.title,r.type,r.competency,r.status].some(v=>String(v).toLowerCase().includes(q))).slice(0,3).forEach(r=>add(r.title,'/trainer/resources'));trainerAssessments.filter(a=>a.ownerId===req.user!.id&&[a.title,a.status,a.competency].some(v=>String(v).toLowerCase().includes(q))).slice(0,3).forEach(a=>add(a.title,'/trainer/assessments'));}else if(req.user!.role==='trainee'){courses.filter(c=>c.status==='Published'&&[c.title,c.description,...c.competencies].some(v=>String(v).toLowerCase().includes(q))).slice(0,4).forEach(c=>add(c.title,`/courses/${c.id}`));trainerAssessments.filter(a=>a.status==='Open'&&enrollments.some(e=>e.courseId===a.courseId&&e.traineeId===req.user!.id)&&[a.title,a.competency].some(v=>String(v).toLowerCase().includes(q))).slice(0,3).forEach(a=>add(a.title,'/trainee/assessments'));}else{users.filter(u=>u.role!=='admin'&&u.status!=='pending'&&[u.name,u.email,u.role,u.status].some(v=>String(v).toLowerCase().includes(q))).slice(0,4).forEach(u=>add(u.name,'/admin/users'));courses.filter(c=>[c.title,c.status,c.trainer].some(v=>String(v).toLowerCase().includes(q))).slice(0,3).forEach(c=>add(c.title,'/admin/courses'));trainerAssessments.filter(a=>[a.title,a.status].some(v=>String(v).toLowerCase().includes(q))).slice(0,3).forEach(a=>add(a.title,'/admin/assessments'));}ok(res,{results:out.slice(0,8)});});
r.get('/auth/me',auth,(req:AuthedRequest,res)=>ok(res,{user:publicUser(req.user!)}));

function roleRequirementsFor(roleName:string){return roleRequirements.filter((r:any)=>r.role.toLowerCase()===roleName.toLowerCase());}
function hasApprovedTrainerAccess(traineeId:string,trainerId:string){return trainingRequests.some((x:any)=>x.traineeId===traineeId&&x.trainerId===trainerId&&x.status==='Approved');}
function presentedDiagnostic(q:any,i:number){const shift=i%4;const options=q.options.map((_:any,j:number)=>q.options[(j+shift)%q.options.length]);return {id:q.id,skill:q.skill,text:q.text,options,correct:(q.correct-shift+q.options.length)%q.options.length};}
function traineeSkillSnapshot(userId:string){const user=users.find(u=>u.id===userId);const roleName=user?.jobRole||'Weather Analyst';const reqs=roleRequirementsFor(roleName);const state:any=traineeProgress[userId]||{competency:55,previous:55,diagnostic:55,competencies:{}};const competenciesMap=state.competencies||{};return {roleName,requirements:reqs.map((r:any)=>{const current=Number(competenciesMap[r.competency]??state.competency??55);const g=Math.max(0,r.required-current);const course=courses.find((c:any)=>c.status==='Published'&&c.competencies?.includes(r.competency));return {...r,current,required:r.required,gap:g,priority:g>=15||r.importance==='High'?'High':g>0?'Moderate':'On target',level:current>=90?'Expert':current>=80?'Advanced':current>=65?'Proficient':current>=50?'Working':'Awareness',course:course?.title||null,courseId:course?.id||null,reason:course?`This course directly covers the ${r.competency} skills below your role target.`:`Build focused practice for ${r.competency}.`};})};}
function buildRoadmap(userId:string){const snap=traineeSkillSnapshot(userId);const gaps=snap.requirements.filter((g:any)=>g.gap>0).sort((a:any,b:any)=>b.gap-a.gap);const steps=gaps.map((g:any,index:number)=>{const course=courses.find((c:any)=>c.status==='Published'&&c.competencies?.includes(g.competency));const trainers=users.filter((u:any)=>u.role==='trainer'&&['active'].includes(u.status as string)).map((u:any)=>{const match=trainerMatches.find((m:any)=>m.id===u.id);const expertise=match?.expertise||u.jobRole;const score=(String(expertise).toLowerCase().includes(String(g.competency).toLowerCase())?95:75);const profile=u.id==='u2'?{qualifications:'Ph.D. Meteorology',experience:'12 years',certifications:['IMD Advanced Training Certification'],performance:91,courses:'Data Processing Fundamentals, Operational Communication'}:u.id==='u6'?{qualifications:'Ph.D. Remote Sensing',experience:'10 years',certifications:['Advanced Satellite Meteorology Certification'],performance:89,courses:'Satellite Meteorology — Advanced, Forecast Interpretation'}:{qualifications:'M.Sc. Climate Science',experience:'8 years',certifications:['Climate Services Training Certification'],performance:86,courses:'Climate and Forecast Applications'};return {id:u.id,name:u.name,score,expertise,reason:match?.reason||`Strong alignment with ${g.competency} training needs.`,department:u.department,jobRole:u.jobRole,...profile};}).sort((a:any,b:any)=>b.score-a.score);return {step:index+1,competency:g.competency,current:g.current,required:g.required,gap:g.gap,priority:g.priority,action:course?`Take ${course.title}`:'Build targeted practice',courseId:course?.id||null,course:course?.title||null,trainer:trainers[0]||null,reason:course?`This learning directly covers the ${g.competency} skills below your role target.`:`Build focused practice for ${g.competency} before reassessment.`};});return {role:snap.roleName,gaps,steps,trainers:[...new Map(steps.filter((x:any)=>x.trainer).map((x:any)=>[x.trainer.id,x.trainer])).values()].slice(0,3)};}

r.get('/trainer/onboarding',auth,role('trainer'),(req:AuthedRequest,res)=>{const p=trainerProfiles[req.user!.id]||{};ok(res,{user:publicUser(req.user!),profile:p});});
r.post('/trainer/onboarding/complete',auth,role('trainer'),(req:AuthedRequest,res)=>{
  const p=z.object({organization:z.string().min(2),department:z.string().trim().min(2),jobRole:z.string().trim().min(2),qualification:z.string().trim().min(2).max(180),experience:z.string().trim().min(2).max(80),expertise:z.string().trim().min(2).max(600),certifications:z.string().max(600).optional().default(''),bio:z.string().max(600).optional().default('')}).safeParse(req.body);
  if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please complete all required trainer profile details.');
  const u=req.user!;u.department=p.data.department;u.jobRole=p.data.jobRole;u.onboardingComplete=true;u.approvalRequired=true;u.status='pending';
  trainerProfiles[u.id]={...p.data,expertise:p.data.expertise.split(',').map(x=>x.trim()).filter(Boolean),certifications:p.data.certifications.split(',').map(x=>x.trim()).filter(Boolean)};
  ok(res,{user:publicUser(u),message:'Trainer profile saved. Your approval request is ready for administrator review.'});
});
r.post('/trainer/request-approval',auth,role('trainer'),(req:AuthedRequest,res)=>{if(!req.user!.onboardingComplete)return fail(res,409,'PROFILE_REQUIRED','Complete your trainer profile first.');req.user!.approvalRequired=true;req.user!.status='pending';ok(res,{status:'pending',message:'Trainer approval requested.'});});

r.post('/trainee/onboarding/complete',auth,role('trainee'),(req:AuthedRequest,res)=>{
  const p=z.object({jobRole:z.string().trim().min(2).max(100),department:z.string().trim().min(2).max(120),qualification:z.string().max(160).optional().default(''),experience:z.string().max(160).optional().default(''),skills:z.string().max(1000).optional().default(''),interests:z.string().max(1000).optional().default(''),certificates:z.string().max(1000).optional().default('')}).safeParse(req.body);
  if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please complete the required onboarding details.');
  const u=req.user!;
  if(u.status!=='pending')return fail(res,409,'PROFILE_LOCKED','Your trainee application is no longer in the onboarding stage.');
  u.jobRole=p.data.jobRole;u.department=p.data.department;u.onboardingComplete=true;u.diagnosticComplete=false;u.diagnosticTestStatus='not_started';u.approvalRequired=true;u.status='pending';
  traineeProfiles[u.id]={qualification:p.data.qualification,experience:p.data.experience,skills:p.data.skills.split(',').map(x=>x.trim()).filter(Boolean),interests:p.data.interests.split(',').map(x=>x.trim()).filter(Boolean),certificates:p.data.certificates.split(',').map(x=>x.trim()).filter(Boolean),organization:organization.name};
  ok(res,{user:publicUser(u),message:'Profile saved. Request administrator approval to continue.'});
});
r.post('/trainee/request-approval',auth,role('trainee'),(req:AuthedRequest,res)=>{
  const u=req.user!;
  if(!u.onboardingComplete)return fail(res,409,'PROFILE_REQUIRED','Complete your trainee profile first.');
  u.approvalRequired=true;u.status='pending';u.diagnosticComplete=false;u.diagnosticTestStatus='not_started';
  ok(res,{status:'pending',message:'Trainee approval requested. An administrator can now review your complete profile.'});
});
r.get('/trainee/profile',auth,role('trainee'),(req:AuthedRequest,res)=>{const u=req.user!;const p=traineeProfiles[u.id]||{qualification:'',experience:'',skills:[],interests:[],certificates:[]};ok(res,{user:publicUser(u),qualifications:p.qualification?[p.qualification]:[],experience:p.experience?[{title:u.jobRole,years:parseFloat(String(p.experience))||0}]:[],skills:p.skills||[],interests:p.interests||[],certificates:(p.certificates||[]).map((x:string,i:number)=>({course:x,issued:'Prior learning',certificateId:`PRIOR-${i+1}`}))});});
r.put('/trainee/profile',auth,role('trainee'),(req:AuthedRequest,res)=>{const p=z.object({department:z.string().min(2),jobRole:z.string().min(2)}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please provide a valid role and department.');req.user!.department=p.data.department;req.user!.jobRole=p.data.jobRole;ok(res,{user:publicUser(req.user!),message:'Profile updated.'});});
r.get('/trainee/dashboard',auth,role('trainee'),(req:AuthedRequest,res)=>{if(req.user!.status==='pending'||req.user!.approvalRequired)return fail(res,403,'APPROVAL_REQUIRED','Your account must be approved before dashboard access.');if(!req.user!.onboardingComplete)return fail(res,409,'ONBOARDING_INCOMPLETE','Complete onboarding before opening your dashboard.');const state:any=traineeProgress[req.user!.id]||{};const snap=traineeSkillSnapshot(req.user!.id);const gaps=snap.requirements;const avg=gaps.length?Math.round(gaps.reduce((a:number,g:any)=>a+g.current,0)/gaps.length):Number((traineeProgress[req.user!.id] as any)?.competency||55);const roadmap=buildRoadmap(req.user!.id);const assessments=trainerAssessments.filter(a=>a.status==='Open'&&enrollments.some(e=>e.courseId===a.courseId&&e.traineeId===req.user!.id)).map(a=>({id:a.id,title:a.title,date:a.deadline,progress:0,trainer:users.find(u=>u.id===a.ownerId)?.name||'Trainer'}));const active=courses.filter(c=>c.status==='Published').map(c=>{const e=enrollments.find(e=>e.courseId===c.id&&e.traineeId===req.user!.id);return e?{...c,progress:e.progress}:null}).filter(Boolean).filter((c:any)=>c.progress>0&&c.progress<100);const topGap=roadmap.steps[0]||null;const diagnosticComplete=state.diagnostic!==undefined&&state.diagnostic!==null;const required=gaps.length?Math.max(...gaps.map((g:any)=>g.required)):80;const safeNext=topGap||{action:'Your diagnostic is complete. Explore your learning roadmap.',courseId:null,competency:null,current:avg,required,gap:0};ok(res,{competency:avg,required,role:snap.roleName,diagnosticComplete,skillGaps:diagnosticComplete?gaps:[],recommendations:diagnosticComplete?roadmap.steps.slice(0,3):[],roadmap,activeCourses:active,nextStep:diagnosticComplete?safeNext:{action:'Complete your role-based diagnostic',courseId:null,competency:null,current:avg,required,gap:0},upcomingAssessments:assessments.slice(0,4),feedback:[{from:'Trainer team',text:'Your next steps are based on the evidence from your diagnostic and learning.'}],certificates:certificates.filter(c=>c.holderId===req.user?.id),notifications:notifications.filter(n=>n.userId===req.user?.id)});});
r.get('/trainee/competencies',auth,role('trainee'),(req:AuthedRequest,res)=>ok(res,{role:traineeSkillSnapshot(req.user!.id).roleName,competencies:traineeSkillSnapshot(req.user!.id).requirements}));
r.get('/trainee/skill-gaps',auth,role('trainee'),(req:AuthedRequest,res)=>ok(res,{role:traineeSkillSnapshot(req.user!.id).roleName,gaps:traineeSkillSnapshot(req.user!.id).requirements.filter((g:any)=>g.gap>0)}));
r.get('/trainee/roadmap',auth,role('trainee'),(req:AuthedRequest,res)=>ok(res,buildRoadmap(req.user!.id)));
r.get('/trainee/recommendations',auth,role('trainee'),(req:AuthedRequest,res)=>{const roadmap=buildRoadmap(req.user!.id);ok(res,{courses:roadmap.steps.map((s:any)=>s.courseId&&courses.find(c=>c.id===s.courseId)).filter(Boolean),trainers:roadmap.trainers,roadmap});});
r.get('/trainee/notifications',auth,role('trainee','trainer','admin'),(req:AuthedRequest,res)=>ok(res,{notifications:notifications.filter(n=>n.userId===req.user?.id)}));
r.get('/trainer/notifications',auth,role('trainer'),(req:AuthedRequest,res)=>ok(res,{notifications:notifications.filter(n=>n.userId===req.user?.id)}));
r.get('/admin/notifications',auth,role('admin'),(req:AuthedRequest,res)=>ok(res,{notifications:notifications.filter(n=>n.userId===req.user?.id)}));
r.post('/feedback',auth,(req:AuthedRequest,res)=>{const p=z.object({objectType:z.enum(['course','content','trainer']),objectId:z.string(),rating:z.number().min(1).max(5),comment:z.string().max(500).optional()}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please provide a rating and comment.');const item={id:`f${Date.now()}`,fromUserId:req.user!.id,...p.data,createdAt:'Just now'};feedback.push(item);ok(res,{feedback:item,message:'Thanks. Your feedback was saved.'});});
r.get('/trainee/feedback',auth,role('trainee'),(req:AuthedRequest,res)=>ok(res,{feedback:feedback.filter(f=>f.fromUserId===req.user?.id)}));
r.get('/trainee/assessments',auth,role('trainee'),(req:AuthedRequest,res)=>{const eligibleCourseIds=new Set(enrollments.filter(e=>e.traineeId===req.user!.id).map(e=>e.courseId));const approvedTrainerIds=new Set(trainingRequests.filter((x:any)=>x.traineeId===req.user!.id&&x.status==='Approved').map((x:any)=>x.trainerId));const eligibleByTrainer=(a:any)=>approvedTrainerIds.has(a.ownerId);const list=trainerAssessments.filter(a=>a.status==='Open'&&(eligibleCourseIds.has(a.courseId)||eligibleByTrainer(a))).map(a=>{const attempts=assessmentAttempts.filter(x=>x.assessmentId===a.id&&x.traineeId===req.user!.id&&x.status==='Evaluated');const latest=attempts.at(-1);const locked=Boolean(latest)&&(Number(latest.score)>=a.passingScore||attempts.length>=a.attemptLimit);return {id:a.id,title:a.title,course:courses.find(c=>c.id===a.courseId)?.title||'Course',trainer:users.find(u=>u.id===a.ownerId)?.name||'Trainer',status:locked?'Result Available':'Open',deadline:a.deadline,score:latest?.score??null,attemptsUsed:attempts.length,questions:a.questions.length,timeLimitMinutes:a.timeLimitMinutes,passingScore:a.passingScore,attemptLimit:a.attemptLimit,eligible:true};});const resultOnly=trainerAssessments.filter(a=>eligibleCourseIds.has(a.courseId)&&assessmentAttempts.some(x=>x.assessmentId===a.id&&x.traineeId===req.user!.id&&x.status==='Evaluated')&&!list.some(x=>x.id===a.id)).map(a=>{const latest=assessmentAttempts.filter(x=>x.assessmentId===a.id&&x.traineeId===req.user!.id&&x.status==='Evaluated').at(-1);return {id:a.id,title:a.title,course:courses.find(c=>c.id===a.courseId)?.title||'Course',trainer:users.find(u=>u.id===a.ownerId)?.name||'Trainer',status:'Result Available',deadline:a.deadline,score:latest?.score??null,attemptsUsed:1,questions:a.questions.length,timeLimitMinutes:a.timeLimitMinutes,passingScore:a.passingScore,attemptLimit:a.attemptLimit,eligible:true};});ok(res,{assessments:[...list,...resultOnly]});});
r.get('/trainee/interventions',auth,role('trainee'),(req:AuthedRequest,res)=>ok(res,{interventions:interventions.filter(i=>i.learnerId===req.user?.id)}));
r.post('/trainee/interventions/:id/complete',auth,role('trainee'),(req:AuthedRequest,res)=>{const item=interventions.find(i=>i.id===req.params.id&&i.learnerId===req.user!.id);if(!item)return fail(res,404,'SUPPORT_NOT_FOUND','We could not find that support step.');item.status='Completed';item.completedAt='Just now';ok(res,{intervention:item,message:'Support step marked complete.'});});
r.get('/trainee/certificates',auth,role('trainee'),(req:AuthedRequest,res)=>ok(res,{certificates:certificates.filter(c=>c.holderId===req.user?.id)}));
r.post('/diagnostic/start',auth,role('trainee'),(req:AuthedRequest,res)=>{if(req.user!.status!=='active')return fail(res,403,'APPROVAL_REQUIRED','Your account must be approved before starting the diagnostic.');if(!req.user!.onboardingComplete)return fail(res,409,'ONBOARDING_REQUIRED','Complete your profile first.');if(req.user!.diagnosticTestStatus==='completed'||traineeProgress[req.user!.id]?.diagnosticComplete)return fail(res,409,'DIAGNOSTIC_ALREADY_COMPLETED','Your diagnostic is already complete.');req.user!.diagnosticTestStatus='in_progress';const questions=diagnosticQuestionBank[req.user!.jobRole]||diagnosticQuestionBank['Weather Analyst'];ok(res,{attemptId:`diag${Date.now()}`,status:'In Progress',role:req.user!.jobRole,questionCount:questions.length});});
r.get('/diagnostic',auth,role('trainee'),(req:AuthedRequest,res)=>{if(req.user!.status!=='active')return fail(res,403,'APPROVAL_REQUIRED','Your account must be approved before starting the diagnostic.');if(!req.user!.onboardingComplete)return fail(res,409,'ONBOARDING_REQUIRED','Complete your profile first.');if(req.user!.diagnosticTestStatus==='completed'||traineeProgress[req.user!.id]?.diagnosticComplete)return fail(res,409,'DIAGNOSTIC_ALREADY_COMPLETED','Your diagnostic is already complete.');const questions=diagnosticQuestionBank[req.user!.jobRole]||diagnosticQuestionBank['Weather Analyst'];const reqs=roleRequirementsFor(req.user!.jobRole);ok(res,{title:`${req.user!.jobRole} Diagnostic`,role:req.user!.jobRole,questions:questions.map((q:any,i:number)=>{const p=presentedDiagnostic(q,i);return {id:p.id,skill:p.skill,text:p.text,options:p.options}}),competencies:reqs});});
r.post('/diagnostic/submit',auth,role('trainee'),(req:AuthedRequest,res)=>{if(req.user!.status!=='active')return fail(res,403,'APPROVAL_REQUIRED','Your account must be approved before submitting the diagnostic.');if(!req.user!.onboardingComplete)return fail(res,409,'ONBOARDING_REQUIRED','Complete your profile first.');if(req.user!.diagnosticTestStatus==='completed'||traineeProgress[req.user!.id]?.diagnosticComplete)return fail(res,409,'DIAGNOSTIC_ALREADY_COMPLETED','Your diagnostic is already complete.');const questions=diagnosticQuestionBank[req.user!.jobRole]||diagnosticQuestionBank['Weather Analyst'];const answers=Array.isArray(req.body.answers)?req.body.answers:[];if(answers.length!==questions.length)return fail(res,400,'INCOMPLETE_DIAGNOSTIC','Answer every diagnostic question before continuing.');const bySkill:any={};questions.forEach((q:any,i:number)=>{const answer=answers[i];const presented=presentedDiagnostic(q,i);const correct=Number(answer?.optionIndex)===presented.correct;bySkill[q.skill]??={correct:0,total:0};bySkill[q.skill].total++;if(correct)bySkill[q.skill].correct++;});const reqs=roleRequirementsFor(req.user!.jobRole);const state:any=traineeProgress[req.user!.id]||{competency:55,previous:55,diagnostic:55,competencies:{}};state.competencies={...(state.competencies||{})};const results=reqs.map((r:any)=>{const evidence=bySkill[r.competency];const current=evidence?Math.round((evidence.correct/evidence.total)*100):55;state.competencies[r.competency]=current;return {...r,current,gap:Math.max(0,r.required-current),priority:(r.required-current)>=15||r.importance==='High'?'High':current<r.required?'Moderate':'On target',level:current>=90?'Expert':current>=80?'Advanced':current>=65?'Proficient':current>=50?'Working':'Awareness'};});const avg=results.length?Math.round(results.reduce((a:number,r:any)=>a+r.current,0)/results.length):55;state.previous=avg;state.diagnostic=avg;state.competency=avg;state.diagnosticComplete=true;req.user!.diagnosticComplete=true;req.user!.diagnosticTestStatus='completed';req.user!.approvalRequired=false;traineeProgress[req.user!.id]=state;const roadmap=buildRoadmap(req.user!.id);ok(res,{score:avg,role:req.user!.jobRole,competencies:results,gaps:roadmap.gaps,roadmap,trainers:roadmap.trainers,message:`Your ${req.user!.jobRole} baseline is ready. We mapped your gaps and built your first learning roadmap.`});});

r.get('/courses',auth,(req:AuthedRequest,res)=>{const q=String(req.query.search||'').toLowerCase();const level=String(req.query.level||'');const mine=String(req.query.mine||'')==='true';let base=req.user!.role==='trainee'?courses.filter(c=>c.status==='Published'):req.user!.role==='trainer'?courses.filter(c=>c.trainerId===req.user!.id):courses;if(req.user!.role==='trainee'&&mine){const ids=new Set(enrollments.filter(e=>e.traineeId===req.user!.id).map(e=>e.courseId));base=base.filter(c=>ids.has(c.id));}const filtered=base.filter(c=>(!q||[c.title,c.description,c.trainer,...c.competencies].some(v=>String(v).toLowerCase().includes(q)))&&(!level||c.level===level));ok(res,{courses:filtered});});
r.get('/courses/:id',auth,(req:AuthedRequest,res)=>{const c=courses.find(x=>x.id===req.params.id);if(!c)return fail(res,404,'COURSE_NOT_FOUND',"We couldn't find this course.");if(req.user!.role==='trainee'&&c.status!=='Published')return fail(res,403,'COURSE_NOT_AVAILABLE','This course is not available to learners yet.');const enrollment=req.user!.role==='trainee'?enrollments.find(e=>e.courseId===c.id&&e.traineeId===req.user!.id):null;const trainerApproved=req.user!.role==='trainee'?hasApprovedTrainerAccess(req.user!.id,c.trainerId):false;const effectiveProgress=enrollment?.progress??0;const completed=Math.ceil(c.modules*effectiveProgress/100);const courseResources=resources.filter(x=>x.courseId===c.id&&x.status==='Published');const assessment=trainerAssessments.find(a=>a.courseId===c.id&&a.status==='Open');ok(res,{...c,progress:effectiveProgress,objectives:c.objectives,modules:Array.from({length:c.modules},(_,i)=>({id:i+1,title:`Module ${i+1} · ${['Core concepts','Data preparation','Validation checks','Operational practice','Quality review','Applied challenge','Reflection','Final review'][i]||'Applied learning'}`,status:i<completed?'Completed':i===completed?'Current':'Locked'})),resources:courseResources.length?courseResources.map(r=>({id:r.id,type:r.type,title:r.title,version:r.version,status:r.status})):[{id:'r1',type:'PDF',title:'Study guide',version:1,status:'Published'}],assessment:(assessment&&req.user!.role!=='trainee'||assessment&&(enrollment||trainerApproved))?{id:assessment.id,title:assessment.title,passingScore:assessment.passingScore}:null,enrolled:!!enrollment,trainerApproved});});
r.post('/courses/:id/enroll',auth,role('trainee'),(req:AuthedRequest,res)=>{const c=courses.find(x=>x.id===req.params.id);if(!c)return fail(res,404,'COURSE_NOT_FOUND',"We couldn't find this course.");if(c.status!=='Published')return fail(res,409,'COURSE_NOT_PUBLISHED','This course is not available yet.');let e=enrollments.find(x=>x.courseId===c.id&&x.traineeId===req.user!.id);if(!e){e={id:`e${Date.now()}`,courseId:c.id,traineeId:req.user!.id,progress:0,status:'In Progress'};enrollments.push(e);}ok(res,{enrolled:true,courseId:c.id,progress:e.progress,message:'You are enrolled. The course is now in My Learning.'});});
r.get('/courses/:id/resources',auth,role('trainee','trainer','admin'),(req:AuthedRequest,res)=>{const c=courses.find(x=>x.id===req.params.id);if(!c)return fail(res,404,'COURSE_NOT_FOUND',"We couldn't find this course.");if(req.user!.role==='trainee'&&!enrollments.some(e=>e.courseId===c.id&&e.traineeId===req.user!.id)&&!hasApprovedTrainerAccess(req.user!.id,c.trainerId))return fail(res,403,'RESOURCE_ACCESS_DENIED','Enroll in the course or get trainer approval before opening its learning resources.');ok(res,{resources:[{id:'r1',type:'PDF',title:'Study guide',access:'Private',version:1},{id:'r2',type:'Presentation',title:'Operational examples',access:'Private',version:2},{id:'r3',type:'Recorded lecture',title:'Core concepts',access:'Private',version:1}]});});
r.put('/courses/:id/progress',auth,role('trainee'),(req:AuthedRequest,res)=>{const p=z.object({progress:z.number().min(0).max(100)}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Progress must be between 0 and 100.');const c=courses.find(x=>x.id===req.params.id&&x.status==='Published');if(!c)return fail(res,404,'COURSE_NOT_FOUND','We could not find this course.');const e=enrollments.find(x=>x.courseId===c.id&&x.traineeId===req.user!.id);if(!e)return fail(res,409,'NOT_ENROLLED','Enroll in this course before updating progress.');e.progress=Math.max(e.progress,p.data.progress);e.status=e.progress>=100?'Completed':'In Progress';ok(res,{progress:e.progress,status:e.status,message:e.progress>=100?'Course completed.':'Learning progress saved.'});});
r.post('/courses/:id/feedback',auth,role('trainee'),(req:AuthedRequest,res)=>{const p=z.object({rating:z.number().min(1).max(5),comment:z.string().max(500).optional()}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please provide a rating from 1 to 5.');const item={id:`f${Date.now()}`,fromUserId:req.user!.id,objectType:'course',objectId:req.params.id,...p.data,createdAt:'Just now'};feedback.push(item);ok(res,{feedback:item,message:'Thanks. Your course feedback was saved.'});});
r.get('/courses/:id/modules',auth,(req,res)=>{const c=courses.find(x=>x.id===req.params.id);if(!c)return fail(res,404,'COURSE_NOT_FOUND',"We couldn't find this course.");ok(res,{modules:Array.from({length:c.modules},(_,i)=>({id:i+1,title:`Module ${i+1}`,status:i<Math.ceil(c.modules*c.progress/100)?'Completed':i===Math.ceil(c.modules*c.progress/100)?'Current':'Locked'}))});});

r.get('/trainer/requests',auth,role('trainer'),(req:AuthedRequest,res)=>{const rows=trainingRequests.filter(x=>x.trainerId===req.user!.id).map(x=>({...x,trainee:users.find(u=>u.id===x.traineeId)?publicUser(users.find(u=>u.id===x.traineeId)!):null}));ok(res,{requests:rows});});
r.post('/trainee/trainers/:id/request',auth,role('trainee'),(req:AuthedRequest,res)=>{const trainer=users.find(u=>u.id===req.params.id&&u.role==='trainer'&&['active'].includes(u.status));if(!trainer)return fail(res,404,'TRAINER_NOT_FOUND','That trainer is not available.');if(!req.user!.diagnosticComplete)return fail(res,409,'DIAGNOSTIC_REQUIRED','Complete your diagnostic before requesting a trainer.');const existing=trainingRequests.find(x=>x.traineeId===req.user!.id&&x.trainerId===trainer.id&&['Pending','Approved'].includes(x.status));if(existing)return ok(res,{request:existing,message:existing.status==='Approved'?'This trainer is already approved for your training.':'Your request is already under review.'});const item={id:`tr${Date.now()}`,traineeId:req.user!.id,trainerId:trainer.id,status:'Pending',message:String(req.body?.message||'I would like training support for my highest-priority skill gap.'),createdAt:'Just now'};trainingRequests.push(item);ok(res,{request:item,message:'Training request sent to the trainer.'});});
r.put('/trainer/requests/:id/status',auth,role('trainer'),(req:AuthedRequest,res)=>{const p=z.object({status:z.enum(['Approved','Declined'])}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Choose Approved or Declined.');const item=trainingRequests.find(x=>x.id===req.params.id&&x.trainerId===req.user!.id);if(!item)return fail(res,404,'REQUEST_NOT_FOUND','We could not find that training request.');item.status=p.data.status;item.updatedAt='Just now';ok(res,{request:item,message:`Training request ${p.data.status.toLowerCase()}.`});});
r.get('/trainer/dashboard',auth,role('trainer'),(req:AuthedRequest,res)=>{const mineCourses=courses.filter(c=>c.trainerId===req.user!.id);const mineCourseIds=new Set(mineCourses.map(c=>c.id));const activeLearnerIds=new Set([...enrollments.filter(e=>mineCourseIds.has(e.courseId)).map(e=>e.traineeId),...trainingRequests.filter((x:any)=>x.trainerId===req.user!.id&&x.status==='Approved').map((x:any)=>x.traineeId)]);const pending=trainerAssessments.filter(a=>a.ownerId===req.user!.id&&['Open','Submitted'].includes(a.status)).length;return ok(res,{userName:req.user!.name,activeLearners:activeLearnerIds.size,courses:mineCourses.length,pendingAssessments:pending,needsSupport:learners.filter(x=>x.status==='Needs Support'&&activeLearnerIds.has(x.id)).length,learners:learners.filter(x=>activeLearnerIds.has(x.id)),performance:[{month:'May',score:61},{month:'Jun',score:65},{month:'Jul',score:69},{month:'Aug',score:73}],deadlines:[{title:'Data Processing Assessment',date:'Tomorrow'},{title:'Monsoon Systems review',date:'Friday'}],recent:[{text:'Ananya received a support plan',time:'1h ago'},{text:'Data Processing assessment evaluated',time:'3h ago'},{text:'New resource added to Data Processing',time:'Yesterday'}]});});
r.get('/trainer/profile',auth,role('trainer'),(req:AuthedRequest,res)=>{const p=trainerProfiles[req.user!.id]||{};ok(res,{user:publicUser(req.user!),...p,qualifications:p.qualification?[p.qualification]:['Professional qualification'],performance:req.user!.id==='u2'?91:req.user!.id==='u6'?89:86});});
r.put('/trainer/profile',auth,role('trainer'),(req:AuthedRequest,res)=>{const p=z.object({department:z.string().min(2),jobRole:z.string().min(2),experience:z.string().optional()}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please check your trainer profile.');req.user!.department=p.data.department;req.user!.jobRole=p.data.jobRole;ok(res,{user:publicUser(req.user!)});});
r.get('/trainer/feedback',auth,role('trainer'),(req:AuthedRequest,res)=>{const rows=feedback.filter(f=>f.trainerId===req.user!.id||f.objectType==='assessment'&&trainerAssessments.some(a=>a.id===f.objectId&&a.ownerId===req.user!.id)).map(f=>({...f,trainee:users.find(u=>u.id===f.fromUserId)?.name||'Trainee',assessment:trainerAssessments.find(a=>a.id===f.objectId)?.title||null,course:trainerAssessments.find(a=>a.id===f.objectId)?courses.find(c=>c.id===trainerAssessments.find(a=>a.id===f.objectId)?.courseId)?.title:null}));ok(res,{feedback:rows});});
r.get('/trainer/learners',auth,role('trainer'),(req:AuthedRequest,res)=>{const q=String(req.query.search||'').trim().toLowerCase();const mineCourseIds=new Set(courses.filter(c=>c.trainerId===req.user!.id).map(c=>c.id));const assignedIds=new Set(enrollments.filter(e=>mineCourseIds.has(e.courseId)).map(e=>e.traineeId));const mine=learners.filter(l=>assignedIds.has(l.id));const filtered=q?mine.filter(l=>[l.name,l.skill,l.status].some(v=>String(v).toLowerCase().includes(q))):mine;ok(res,{learners:filtered});});
r.get('/trainer/learners/:id',auth,role('trainer'),(req,res)=>{const l=learners.find(x=>x.id===req.params.id);if(!l)return fail(res,404,'USER_NOT_FOUND','We could not find that learner.');const u=users.find(x=>x.id===l.id);const snap=traineeSkillSnapshot(l.id);const attempts=assessmentAttempts.filter(a=>a.traineeId===l.id&&a.status==='Evaluated').map(a=>({title:trainerAssessments.find(x=>x.id===a.assessmentId)?.title||'Assessment',score:a.score,status:a.status}));ok(res,{profile:{...l,role:u?.jobRole},courses:enrollments.filter(e=>e.traineeId===l.id).map(e=>courses.find(c=>c.id===e.courseId)).filter(Boolean),assessments:attempts,competencies:snap.requirements,interventions:interventions.filter(i=>i.learnerId===l.id),reassessment:{available:interventions.filter(i=>i.learnerId===l.id).length>0&&interventions.filter(i=>i.learnerId===l.id).every(i=>i.status==='Completed'),previous:traineeProgress[l.id]?.competency||55,target:Math.max(...snap.requirements.map((x:any)=>x.required),80)}});});
r.get('/trainer/support',auth,role('trainer'),(req:AuthedRequest,res)=>{const mineCourseIds=new Set(courses.filter(c=>c.trainerId===req.user!.id).map(c=>c.id));const assignedIds=new Set(enrollments.filter(e=>mineCourseIds.has(e.courseId)).map(e=>e.traineeId));ok(res,{learners:learners.filter(l=>l.status==='Needs Support'&&assignedIds.has(l.id)),interventions:interventions.filter(i=>i.trainerId===req.user!.id)});});
r.post('/trainer/interventions',auth,role('trainer'),(req:AuthedRequest,res)=>{const p=z.object({learnerId:z.string(),action:z.string().min(2),message:z.string().min(2).max(500)}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Add a support action and message.');const mineCourseIds=new Set(courses.filter(c=>c.trainerId===req.user!.id).map(c=>c.id));if(!enrollments.some(e=>e.traineeId===p.data.learnerId&&mineCourseIds.has(e.courseId)))return fail(res,403,'LEARNER_NOT_ASSIGNED','You can only support learners enrolled in one of your courses.');const item={id:`i${Date.now()}`,...p.data,trainerId:req.user!.id,status:'Assigned',createdAt:'Just now'};interventions.unshift(item);notifications.push({id:`n${Date.now()}`,userId:p.data.learnerId,title:'Support plan assigned',body:p.data.message,time:'Just now',read:false});ok(res,{assigned:true,intervention:item,message:'Support plan assigned successfully.'});});
r.get('/trainer/courses',auth,role('trainer'),(req:AuthedRequest,res)=>{const q=String(req.query.search||'').trim().toLowerCase();const mine=courses.filter(c=>c.trainerId===req.user!.id);const filtered=q?mine.filter(c=>[c.title,c.description,c.status].some(v=>String(v).toLowerCase().includes(q))):mine;ok(res,{courses:filtered});});
r.post('/trainer/courses',auth,role('trainer'),(req:AuthedRequest,res)=>{const p=z.object({title:z.string().min(3),description:z.string().min(10),level:z.string().min(2),duration:z.string().min(2),objectives:z.union([z.string(),z.array(z.string())]).optional(),competency:z.string().min(2).optional(),modules:z.array(z.string()).optional(),assessmentId:z.string().optional()}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please complete the course details.');const objectives=Array.isArray(p.data.objectives)?p.data.objectives:p.data.objectives?.split('\n').map(x=>x.trim()).filter(Boolean)||['Build practical understanding'];const moduleTitles=p.data.modules?.filter(Boolean)||['Core concepts','Applied practice'];const c:any={id:`course${Date.now()}`,...p.data,objectives,moduleTitles,modules:moduleTitles.length,competencies:[p.data.competency||'Data Processing'],trainerId:req.user!.id,trainer:req.user!.name,progress:0,learners:0,status:'Draft',recommended:false,prerequisites:'None'};courses.unshift(c);ok(res,{course:c,message:'Course saved as a draft.'});});
r.get('/trainer/resources',auth,role('trainer'),(req:AuthedRequest,res)=>{const q=String(req.query.search||'').trim().toLowerCase();const mine=resources.filter(x=>x.ownerId===req.user!.id);const filtered=q?mine.filter(x=>[x.title,x.type,x.competency,x.status].some(v=>String(v).toLowerCase().includes(q))):mine;ok(res,{resources:filtered});});
r.put('/trainer/resources/:id/publish',auth,role('trainer'),(req:AuthedRequest,res)=>{const item=resources.find(x=>x.id===req.params.id&&x.ownerId===req.user!.id);if(!item)return fail(res,404,'RESOURCE_NOT_FOUND','We could not find that resource.');item.status='Published';ok(res,{resource:item,message:'Resource published.'});});
r.post('/trainer/resources',auth,role('trainer'),(req:AuthedRequest,res)=>{const p=z.object({courseId:z.string(),title:z.string().min(2),type:z.enum(['Recorded lecture','Presentation','PDF','Document','Notes','Reference material','Study material']),competency:z.string().min(2),access:z.enum(['Private','Course learners']).default('Private'),fileName:z.string().max(255).optional(),description:z.string().max(500).optional()}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please provide valid resource details.');const course=courses.find(c=>c.id===p.data.courseId&&c.trainerId===req.user!.id);if(!course)return fail(res,404,'COURSE_NOT_FOUND','Choose one of your courses.');const previous=resources.filter(x=>x.ownerId===req.user!.id&&x.courseId===p.data.courseId&&x.title.toLowerCase()===p.data.title.toLowerCase());const item={id:`r${Date.now()}`,ownerId:req.user!.id,...p.data,status:'Draft',version:previous.length?Math.max(...previous.map(x=>x.version))+1:1};resources.unshift(item);ok(res,{resource:item,message:'Resource saved as a draft.'});});
r.get('/trainer/assessments',auth,role('trainer'),(req:AuthedRequest,res)=>{const q=String(req.query.search||'').trim().toLowerCase();const mine=trainerAssessments.filter(x=>x.ownerId===req.user!.id);const withCourse=mine.map(x=>({...x,course:courses.find(c=>c.id===x.courseId)?.title||'Course',questionsCount:Array.isArray(x.questions)?x.questions.length:0,eligibleLearners:enrollments.filter(e=>e.courseId===x.courseId).length}));const filtered=q?withCourse.filter(x=>[x.title,x.course,x.status].some(v=>String(v).toLowerCase().includes(q))):withCourse;ok(res,{assessments:filtered});});
r.put('/trainer/assessments/:id/publish',auth,role('trainer'),(req:AuthedRequest,res)=>{const a=trainerAssessments.find(x=>x.id===req.params.id&&x.ownerId===req.user!.id);if(!a)return fail(res,404,'ASSESSMENT_NOT_FOUND','We could not find that assessment.');if(!['Draft','Submitted'].includes(a.status))return fail(res,409,'ASSESSMENT_STATE_INVALID','This assessment is already published.');a.status='Open';ok(res,{assessment:a,message:'Assessment published and available to eligible learners.'});});
r.post('/trainer/assessments',auth,role('trainer'),(req:AuthedRequest,res)=>{const p=z.object({courseId:z.string(),title:z.string().min(3),instructions:z.string().min(5),competency:z.string().min(2),deadline:z.string().min(3),timeLimitMinutes:z.number().int().min(1).max(600),passingScore:z.number().min(0).max(100),attemptLimit:z.number().int().min(1).max(10),questions:z.array(z.object({text:z.string().min(3),skill:z.string().min(2),options:z.array(z.string().min(1)).length(4),correct:z.number().int().min(0).max(3),marks:z.number().positive()})).min(1)}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please complete the assessment details and every question.');const course=courses.find(c=>c.id===p.data.courseId&&c.trainerId===req.user!.id);if(!course)return fail(res,404,'COURSE_NOT_FOUND','Choose one of your courses.');const parsedDeadline=new Date(p.data.deadline);const assessment={id:`assess${Date.now()}`,ownerId:req.user!.id,...p.data,deadlineAt:Number.isNaN(parsedDeadline.getTime())?undefined:p.data.deadline,deadline:Number.isNaN(parsedDeadline.getTime())?p.data.deadline:parsedDeadline.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}),status:'Draft'};trainerAssessments.unshift(assessment);ok(res,{assessment,message:'Assessment saved as a draft.'});});

r.get('/assessments/:id',auth,role('trainee','trainer','admin'),(req:AuthedRequest,res)=>{const a=trainerAssessments.find(x=>x.id===req.params.id);if(!a||a.status!=='Open')return fail(res,404,'ASSESSMENT_NOT_AVAILABLE','This assessment is not available.');if(req.user!.role==='trainee'&&!enrollments.some(e=>e.courseId===a.courseId&&e.traineeId===req.user!.id))return fail(res,403,'ASSESSMENT_NOT_ASSIGNED','This assessment is available only to learners enrolled in its course.');ok(res,{id:a.id,title:a.title,instructions:a.instructions,course:courses.find(c=>c.id===a.courseId)?.title||'Course',competency:a.competency,deadline:a.deadline,timeLimitMinutes:a.timeLimitMinutes,passingScore:a.passingScore,attemptLimit:a.attemptLimit,questions:a.questions.map((q:any,i:number)=>({id:`${a.id}-q${i+1}`,skill:q.skill,text:q.text,options:q.options.map((text:string,j:number)=>({id:String.fromCharCode(97+j),text}))}))});});
r.post('/assessments/:id/start',auth,role('trainee'),(req:AuthedRequest,res)=>{const a=trainerAssessments.find(x=>x.id===req.params.id&&x.status==='Open');if(!a)return fail(res,404,'ASSESSMENT_NOT_AVAILABLE','This assessment is not available.');if(!enrollments.some(e=>e.courseId===a.courseId&&e.traineeId===req.user!.id))return fail(res,403,'ASSESSMENT_NOT_ASSIGNED','Enroll in the related course before attempting this assessment.');const deadlineAt=a.deadlineAt?new Date(a.deadlineAt):null;if(deadlineAt&&!Number.isNaN(deadlineAt.getTime())&&Date.now()>deadlineAt.getTime())return fail(res,409,'ASSESSMENT_CLOSED','This assessment deadline has passed.');const prior=assessmentAttempts.filter(x=>x.assessmentId===a.id&&x.traineeId===req.user!.id);if(prior.some(x=>x.status==='In Progress'))return ok(res,{attemptId:prior.find(x=>x.status==='In Progress').id,status:'In Progress',startedAt:prior.find(x=>x.status==='In Progress').startedAt,resumed:true});if(prior.length>=a.attemptLimit)return fail(res,409,'ATTEMPT_LIMIT_REACHED','You have used all allowed attempts.');const attempt:any={id:`att${Date.now()}`,assessmentId:a.id,traineeId:req.user!.id,status:'In Progress',startedAt:new Date().toISOString()};assessmentAttempts.push(attempt);ok(res,{attemptId:attempt.id,status:attempt.status,startedAt:attempt.startedAt});});
r.post('/assessments/:id/submit',auth,role('trainee'),(req:AuthedRequest,res)=>{const a=trainerAssessments.find(x=>x.id===req.params.id&&x.status==='Open');if(!a)return fail(res,404,'ASSESSMENT_NOT_AVAILABLE','This assessment is not available.');if(!enrollments.some(e=>e.courseId===a.courseId&&e.traineeId===req.user!.id)&&!hasApprovedTrainerAccess(req.user!.id,a.ownerId))return fail(res,403,'ASSESSMENT_NOT_ASSIGNED','Enroll in the related course or get trainer approval before submitting this assessment.');const answers=Array.isArray(req.body.answers)?req.body.answers:[];if(answers.length!==a.questions.length)return fail(res,400,'INCOMPLETE_ASSESSMENT','Answer every question before submitting.');const attempt=[...assessmentAttempts].reverse().find(x=>x.assessmentId===a.id&&x.traineeId===req.user!.id&&x.status==='In Progress');if(!attempt)return fail(res,409,'ATTEMPT_NOT_STARTED','Start the assessment before submitting.');const score=Math.round(answers.reduce((sum:any,item:any)=>{const q=a.questions.find((qq:any)=>`${a.id}-q${a.questions.indexOf(qq)+1}`===item.questionId);return sum+(q&&q.options[q.correct]===q.options.find((_:any,j:number)=>String.fromCharCode(97+j)===item.optionId)?q.marks:0)},0)/a.questions.reduce((sum:any,q:any)=>sum+q.marks,0)*100);attempt.status='Evaluated';attempt.score=score;attempt.completedAt=new Date().toISOString();const pass=score>=a.passingScore;const focusAreas=a.questions.filter((q:any,i:number)=>{const item=answers.find((x:any)=>x.questionId===`${a.id}-q${i+1}`);return !item||String.fromCharCode(97+q.correct)!==item.optionId}).map((q:any)=>q.skill);const state:any=traineeProgress[req.user!.id]||{competency:63,previous:63,diagnostic:63,competencies:{}};state.competencies={...(state.competencies||{})};const old=Number(state.competencies[a.competency]??state.competency);if(pass){state.competencies[a.competency]=Math.max(old,Math.min(100,old+Math.max(3,Math.round((100-old)*0.2))));}state.previous=old;state.competency=Math.round(Object.values(state.competencies).reduce((sum:number,v:any)=>sum+Number(v),0)/Math.max(1,Object.keys(state.competencies).length));traineeProgress[req.user!.id]=state;ok(res,{attemptId:attempt.id,score,passed:pass,title:a.title,course:courses.find(c=>c.id===a.courseId)?.title||'Course',focusAreas:[...new Set(focusAreas)].slice(0,3),competencyAfter:state.competencies[a.competency],message:'Assessment submitted. Your result is ready.'});});

r.post('/assessments/:id/feedback',auth,role('trainee'),(req:AuthedRequest,res)=>{const a=trainerAssessments.find(x=>x.id===req.params.id);if(!a)return fail(res,404,'ASSESSMENT_NOT_FOUND','We could not find this assessment.');const attempt=assessmentAttempts.find(x=>x.id===req.body?.attemptId&&x.traineeId===req.user!.id&&x.assessmentId===a.id&&x.status==='Evaluated');if(!attempt)return fail(res,409,'ATTEMPT_REQUIRED','Complete the assessment before leaving feedback.');const p=z.object({rating:z.number().int().min(1).max(5),comment:z.string().max(500).optional()}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please provide a rating from 1 to 5.');const item={id:`f${Date.now()}`,fromUserId:req.user!.id,trainerId:a.ownerId,objectType:'assessment',objectId:a.id,attemptId:attempt.id,rating:p.data.rating,comment:p.data.comment||'',score:attempt.score,createdAt:'Just now'};feedback.push(item);ok(res,{feedback:item,message:'Your assessment feedback was sent to the trainer.'});});
r.get('/reassessments/status',auth,role('trainee'),(req:AuthedRequest,res)=>{const state:any=traineeProgress[req.user!.id]||{competency:55,previous:55,diagnostic:55,competencies:{}};const mine=interventions.filter(i=>i.learnerId===req.user!.id);const available=mine.length>0&&mine.every(i=>i.status==='Completed');const snap=traineeSkillSnapshot(req.user!.id);const target=snap.requirements.filter((g:any)=>g.gap>0).sort((a:any,b:any)=>b.gap-a.gap)[0]||snap.requirements[0];const current=target?Number(state.competencies?.[target.competency]??target.current):state.competency;ok(res,{available,competency:target?.competency||null,previous:current,required:target?.required||80,supportSteps:mine.length,completedSteps:mine.filter(i=>i.status==='Completed').length});});
r.post('/reassessments/:id/submit',auth,role('trainee'),(req:AuthedRequest,res)=>{const mine=interventions.filter(i=>i.learnerId===req.user!.id);if(!mine.length||mine.some(i=>i.status!=='Completed'))return fail(res,409,'SUPPORT_INCOMPLETE','Complete your support plan before taking the reassessment.');const state:any=traineeProgress[req.user!.id]||{competency:55,previous:55,diagnostic:55,competencies:{}};const snap=traineeSkillSnapshot(req.user!.id);const target=snap.requirements.find((g:any)=>g.competency===req.params.id)||snap.requirements.filter((g:any)=>g.gap>0).sort((a:any,b:any)=>b.gap-a.gap)[0];if(!target)return fail(res,404,'REASSESSMENT_TARGET_NOT_FOUND','There is no competency waiting for reassessment.');const previous=Number(state.competencies?.[target.competency]??target.current);const current=Math.min(target.required,previous+10);state.competencies={...(state.competencies||{}),[target.competency]:current};state.previous=previous;state.competency=Math.round(Object.values(state.competencies).reduce((sum:number,v:any)=>sum+Number(v),0)/Object.keys(state.competencies).length);traineeProgress[req.user!.id]=state;const learner=learners.find(l=>l.id===req.user!.id);if(learner){learner.current=current;learner.required=target.required;learner.progress=Math.min(100,learner.progress+8);learner.status=current>=target.required?'On Track':'Needs Support';}ok(res,{score:Math.min(100,current+3),previous,growth:current-previous,currentCompetency:current,competency:target.competency,required:target.required,certificateEligible:false,message:`Great progress. Your ${target.competency} competency increased by ${current-previous} points.`});});

r.get('/admin/profile',auth,role('admin'),(req:AuthedRequest,res)=>{const u=req.user!;ok(res,{user:publicUser(u),organization:organization.name,department:u.department,jobRole:u.jobRole,contactEmail:u.email,role:'Administrator',responsibilities:['Manage organizational access','Define role requirements','Monitor learning and capacity','Review user applications']});});
r.get('/admin/dashboard',auth,role('admin'),(_,res)=>{const trainees=users.filter(u=>u.role==='trainee');const trainers=users.filter(u=>u.role==='trainer'&&['active'].includes(u.status as string));const publishedCourses=courses.filter(c=>c.status==='Published');const issued=certificates.length;const totalEnrollments=enrollments.length;const completed=enrollments.filter(e=>e.progress>=100).length;const evaluated=assessmentAttempts.filter(a=>a.status==='Evaluated');const avgAssessment=evaluated.length?Math.round(evaluated.reduce((n:number,a:any)=>n+Number(a.score||0),0)/evaluated.length):0;const allScores=trainees.flatMap(u=>Object.values((traineeProgress[u.id] as any)?.competencies||{}).map(Number));const avgCompetency=allScores.length?Math.round(allScores.reduce((a:number,b:number)=>a+b,0)/allScores.length):0;const priorityGaps=trainees.reduce((n,u)=>n+traineeSkillSnapshot(u.id).requirements.filter((g:any)=>g.gap>=15).length,0);const compNames=[...new Set(roleRequirements.map((r:any)=>r.competency))];const competency=compNames.slice(0,4).map(name=>{const rows=trainees.flatMap(u=>traineeSkillSnapshot(u.id).requirements.filter((g:any)=>g.competency===name));return {name,value:rows.length?Math.round(rows.reduce((n:number,x:any)=>n+x.current,0)/rows.length):0,target:rows.length?Math.max(...rows.map((x:any)=>x.required)):80};});const trainingDemand=compNames.map(name=>({name,value:trainees.reduce((n,u)=>n+(traineeSkillSnapshot(u.id).requirements.some((g:any)=>g.competency===name&&g.gap>0)?1:0),0)})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value).slice(0,5);ok(res,{kpis:{trainees:trainees.length,trainers:trainers.length,courses:publishedCourses.length,certificates:issued,averageCompetency:avgCompetency,priorityGaps,activeUsers:users.filter(u=>['active'].includes(u.status as string)).length,enrollments:totalEnrollments,completionRate:totalEnrollments?Math.round(completed/totalEnrollments*100):0,assessmentParticipation:trainees.length?Math.min(100,Math.round(assessmentAttempts.length/trainees.length*100)):0,averageAssessment:avgAssessment},competency,trainingDemand,recent:[{text:`${publishedCourses.length} published courses available`,time:'Now'},{text:`${trainers.length} trainers active`,time:'Now'},{text:`${issued} certificates issued`,time:'Now'}]});});
r.get('/admin/users',auth,role('admin'),(_,res)=>ok(res,{users:users.filter(u=>u.role!=='admin'&&['active','suspended'].includes(u.status as string)).map(publicUser),pending:users.filter(u=>u.role!=='admin'&&u.status==='pending').map(publicUser)}));
r.get('/admin/users/:id/profile',auth,role('admin'),(req,res)=>{const u=users.find(x=>x.id===req.params.id);if(!u)return fail(res,404,'USER_NOT_FOUND','We could not find that user.');const profile=u.role==='trainer'?(trainerProfiles[u.id]||{}):(traineeProfiles[u.id]||{});const roadmap=u.role==='trainee'&&u.diagnosticComplete?buildRoadmap(u.id).steps:[];const data:any={user:publicUser(u),profile,roadmap};if(u.role==='trainee')data.diagnosticComplete=!!u.diagnosticComplete;ok(res,data);});
r.get('/admin/approvals',auth,role('admin'),(_,res)=>{const pending=users.filter(u=>u.status==='pending');ok(res,{trainees:pending.filter(u=>u.role==='trainee').map(publicUser),trainers:pending.filter(u=>u.role==='trainer').map(u=>({...publicUser(u),profile:trainerProfiles[u.id]||null}))});});
r.put('/admin/users/:id/status',auth,role('admin'),(req,res)=>{const p=z.object({status:z.enum(['active','pending','suspended','disabled','rejected'])}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Invalid account status.');const u=users.find(x=>x.id===req.params.id);if(!u)return fail(res,404,'USER_NOT_FOUND','We could not find that user.');u.status=p.data.status;if(u.status==='active'){u.approvalRequired=false;if(u.role==='trainee'){u.diagnosticTestStatus=u.diagnosticTestStatus==='completed'?'completed':'not_started';u.diagnosticComplete=u.diagnosticTestStatus==='completed';}}ok(res,{user:publicUser(u)});});
r.put('/admin/users/:id/role',auth,role('admin'),(req:AuthedRequest,res)=>{if(req.params.id===req.user!.id)return fail(res,409,'ROLE_CHANGE_BLOCKED','You cannot change your own administrator role.');const p=z.object({role:z.enum(['trainee','trainer','admin'])}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Invalid role.');const u=users.find(x=>x.id===req.params.id);if(!u)return fail(res,404,'USER_NOT_FOUND','We could not find that user.');u.role=p.data.role;ok(res,{user:publicUser(u)});});
r.get('/admin/roles',auth,role('admin'),(_,res)=>ok(res,{roles:[...new Set(roleRequirements.map(x=>x.role))],requirements:roleRequirements}));
r.post('/admin/roles/requirements',auth,role('admin'),(req,res)=>{const p=z.object({role:z.string().min(2),department:z.string().min(2),competency:z.string().min(2),required:z.number().min(0).max(100),importance:z.enum(['High','Medium','Low'])}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please provide a role, competency and required level.');const item={id:`rr${Date.now()}`,...p.data};roleRequirements.push(item);ok(res,{requirement:item,message:'Role requirement saved.'});});
r.put('/admin/roles/requirements/:id',auth,role('admin'),(req,res)=>{const item=roleRequirements.find(x=>x.id===req.params.id);if(!item)return fail(res,404,'REQUIREMENT_NOT_FOUND','We could not find that requirement.');const p=z.object({required:z.number().min(0).max(100),importance:z.enum(['High','Medium','Low'])}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please provide a valid target level.');Object.assign(item,p.data);ok(res,{requirement:item,message:'Role requirement updated.'});});
r.get('/admin/competencies',auth,role('admin'),(_,res)=>ok(res,{domains:['Data & Technology','Meteorology','Professional Skills','Remote Sensing'],competencies}));
r.post('/admin/competencies',auth,role('admin'),(req,res)=>{const p=z.object({name:z.string().min(2),domain:z.string().min(2),required:z.number().min(0).max(100)}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please provide a competency name, domain and required level.');ok(res,{competency:{id:`c${Date.now()}`,name:p.data.name,domain:p.data.domain,current:0,required:p.data.required,level:'Awareness',gap:p.data.required,priority:'High'}});});
r.put('/trainer/courses/:id/publish',auth,role('trainer'),(req:AuthedRequest,res)=>{const c=courses.find(x=>x.id===req.params.id&&x.trainerId===req.user!.id);if(!c)return fail(res,404,'COURSE_NOT_FOUND','We could not find that course.');if(!['Draft','Submitted'].includes(c.status))return fail(res,409,'COURSE_STATE_INVALID','This course is already published.');c.status='Published';ok(res,{course:c,message:'Course published and available to eligible learners.'});});
r.get('/admin/courses',auth,role('admin'),(_,res)=>ok(res,{courses}));
r.get('/admin/assessments',auth,role('admin'),(_,res)=>ok(res,{assessments:trainerAssessments.map(a=>({id:a.id,title:a.title,course:courses.find(c=>c.id===a.courseId)?.title||'Course',status:a.status,questions:a.questions.length,deadline:a.deadline,passingScore:a.passingScore}))}));
r.get('/admin/certificates',auth,role('admin'),(_,res)=>ok(res,{certificates,summary:{issued:119,verificationRate:98,certificationRate:64}}));
r.post('/admin/announcements',auth,role('admin'),(req,res)=>{const p=z.object({title:z.string().min(3),body:z.string().min(5),audience:z.string().min(2)}).safeParse(req.body);if(!p.success)return fail(res,400,'VALIDATION_ERROR','Please complete the announcement.');const a={id:`a${Date.now()}`,...p.data,createdAt:'Just now'};announcements.unshift(a);ok(res,{announcement:a});});
r.get('/admin/announcements',auth,role('admin'),(_,res)=>ok(res,{announcements}));
r.get('/admin/analytics',auth,role('admin'),(_,res)=>{const base=users.filter(u=>u.role==='trainee').flatMap(u=>Object.values((traineeProgress[u.id] as any)?.competencies||{}).map(Number));const avg=base.length?Math.round(base.reduce((a:number,b:number)=>a+b,0)/base.length):0;const trend=[{month:'Baseline',score:Math.max(0,avg-10)},{month:'Learning',score:Math.max(0,avg-6)},{month:'Assessment',score:Math.max(0,avg-3)},{month:'Current',score:avg}];const courseCompletion=courses.filter(c=>c.status==='Published').map(c=>{const es=enrollments.filter(e=>e.courseId===c.id);return {course:c.title,value:es.length?Math.round(es.filter(e=>e.progress>=100).length/es.length*100):0};});ok(res,{competencyTrend:trend,courseCompletion});});
r.get('/admin/capacity',auth,role('admin'),(_,res)=>{const roles=[...new Set(roleRequirements.map((r:any)=>r.role))];const names=[...new Set(roleRequirements.map((r:any)=>r.competency))];const heatmap=names.map(name=>[name,...roles.map(roleName=>{const rows=users.filter(u=>u.role==='trainee'&&u.jobRole===roleName).flatMap(u=>traineeSkillSnapshot(u.id).requirements.filter((g:any)=>g.competency===name));return rows.length?Math.round(rows.reduce((n:number,x:any)=>n+x.current,0)/rows.length):0;})]);const demand=names.map(name=>({name,value:users.filter(u=>u.role==='trainee').filter(u=>traineeSkillSnapshot(u.id).requirements.some((g:any)=>g.competency===name&&g.gap>0)).length})).sort((a,b)=>b.value-a.value).slice(0,5);const vals=users.filter(u=>u.role==='trainee').flatMap(u=>traineeSkillSnapshot(u.id).requirements);const coverage=vals.length?Math.round(vals.reduce((n:number,x:any)=>n+Math.min(100,x.current/x.required*100),0)/vals.length):0;ok(res,{heatmap,roles,demand,coverage,growth:10});});
r.get('/admin/trainer-matches',auth,role('admin'),(_,res)=>ok(res,{matches:trainerMatches.filter((t:any)=>users.some(u=>u.id===t.id&&['active'].includes(u.status as string))).map(t=>({...t,score:trainerMatch(94,90,92,88,95,90,93)})),weights:{subject:30,level:20,experience:15,qualification:10,certification:10,performance:10,feedback:5}}));

r.post('/trainee/certificates/:courseId/generate',auth,role('trainee'),(req:AuthedRequest,res)=>{const course=courses.find(c=>c.id===req.params.courseId&&c.status==='Published');if(!course)return fail(res,404,'COURSE_NOT_FOUND','We could not find this course.');const enrollment=enrollments.find(e=>e.courseId===course.id&&e.traineeId===req.user!.id);const assessment=trainerAssessments.find(x=>x.courseId===course.id&&x.status==='Open')||trainerAssessments.find(x=>x.courseId===course.id);const passed=assessment?assessmentAttempts.some(a=>a.traineeId===req.user!.id&&a.assessmentId===assessment.id&&a.status==='Evaluated'&&a.score>=assessment.passingScore):false;const state:any=traineeProgress[req.user!.id]||{competency:63,previous:63,diagnostic:55,competencies:{}};const courseCompetency=course.competencies?.[0];const current=Number(state.competencies?.[courseCompetency]??state.competency);const required=roleRequirementsFor(req.user!.jobRole).find((r:any)=>r.competency===courseCompetency)?.required||80;if(!enrollment||enrollment.progress<100||!passed||current<required)return fail(res,409,'CERTIFICATE_NOT_ELIGIBLE','Complete the course, pass its assessment and meet the required competency level first.');const existing=certificates.find(c=>c.holderId===req.user!.id&&c.course===course.title);if(existing)return ok(res,{certificate:existing,message:'Your certificate already exists.'});const certificate={id:`cert${Date.now()}`,certificateId:`CC-2026-${String(10000+certificates.length+1).padStart(5,'0')}`,holderId:req.user!.id,holder:req.user!.name,course:course.title,issued:new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}),valid:true};certificates.push(certificate);ok(res,{certificate,message:'Certificate generated successfully.'});});
r.get('/certificates/:id/verify',(req,res)=>{const c=certificates.find(x=>x.certificateId===req.params.id);if(!c)return ok(res,{valid:false,certificateId:req.params.id});ok(res,c);});
export default r;
