import {ReactNode,useEffect,useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {BarChart3,Bell,BookOpen,BrainCircuit,ChevronDown,ClipboardCheck,FileBadge,Home,LogOut,Menu,MessageSquare,Search,Settings,Target,ListChecks,UserRound,Users,X} from 'lucide-react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {Logo} from '../components/brand';
import {User} from '../lib/types';
import {get} from '../lib/api';
import React from 'react';
class PageErrorBoundary extends React.Component<{children:ReactNode},{hasError:boolean}>{state={hasError:false};static getDerivedStateFromError(){return {hasError:true}};componentDidCatch(error:unknown){console.error('Capacity Connect page error',error)};render(){if(this.state.hasError)return <div className="grid min-h-[calc(100vh-170px)] place-items-center p-6"><div className="w-full max-w-md rounded-3xl border border-line bg-white p-8 text-center shadow-soft"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-red-50 text-red-700">!</div><h2 className="mt-5 font-display text-2xl font-bold">This page could not load</h2><p className="mt-2 text-sm leading-6 text-muted">The rest of Capacity Connect is still available. Try this page again.</p><button className="mt-5 rounded-xl bg-brand px-4 py-2.5 text-sm font-semibold text-white" onClick={()=>this.setState({hasError:false})}>Try Again</button></div></div>;return this.props.children}}


const maps={
 trainee:[['Overview','/trainee/dashboard',Home],['My Learning','/trainee/learning',BookOpen],['Explore Courses','/trainee/courses',BookOpen],['Your Skills','/trainee/skills',BrainCircuit],['Skill Gaps','/trainee/gaps',Target],['Assessments','/trainee/assessments',ClipboardCheck],['Find a Trainer','/trainee/trainers',Users],['Certificates','/trainee/certificates',FileBadge],['Improvement Plan','/trainee/interventions',ListChecks],['My Roadmap','/trainee/roadmap',Target]],
 trainer:[['Overview','/trainer/dashboard',Home],['Learners','/trainer/learners',Users],['Courses','/trainer/courses',BookOpen],['Resources','/trainer/resources',BookOpen],['Assessments','/trainer/assessments',ClipboardCheck],['Feedback','/trainer/feedback',MessageSquare],['Support','/trainer/support',MessageSquare]],
 admin:[['Overview','/admin/dashboard',Home],['Users','/admin/users',Users],['Roles & Requirements','/admin/roles',Target],['Courses','/admin/courses',BookOpen],['Assessments','/admin/assessments',ClipboardCheck],['Certificates','/admin/certificates',FileBadge],['Announcements','/admin/announcements',MessageSquare],['Analytics','/admin/analytics',BarChart3],['Capacity','/admin/capacity',BarChart3],['Approvals','/admin/approvals',Users]],
} as const;

const searchItems=(role:User['role'])=>({
 trainee:[['My Learning','/trainee/learning'],['Explore Courses','/trainee/courses'],['Your Skills','/trainee/skills'],['Skill Gaps','/trainee/gaps'],['Assessments','/trainee/assessments'],['Find a Trainer','/trainee/trainers'],['Certificates','/trainee/certificates']],
 trainer:[['Learners','/trainer/learners'],['Courses','/trainer/courses'],['Add Resource','/trainer/resources/new'],['Resource Library','/trainer/resources'],['Create Assessment','/trainer/assessments/new'],['Assessments','/trainer/assessments'],['Feedback','/trainer/feedback'],['Support','/trainer/support']],
 admin:[['Users','/admin/users'],['Roles & Requirements','/admin/roles'],['Courses','/admin/courses'],['Assessments','/admin/assessments'],['Certificates','/admin/certificates'],['Analytics','/admin/analytics'],['Organizational Capacity','/admin/capacity'],['Approvals','/admin/approvals']],
}[role]);

export function AppShell({user,children}:{user:User;children:ReactNode}){
 const [open,setOpen]=useState(false); const [profileOpen,setProfileOpen]=useState(false); const [search,setSearch]=useState(''); const [searchOpen,setSearchOpen]=useState(false); const loc=useLocation(); const nav=useNavigate(); const items=maps[user.role];
 const signOut=()=>{localStorage.removeItem('cc_token');localStorage.removeItem('cc_user');nav('/')};
 useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'auto'});},[loc.pathname]);
 const title=loc.pathname.split('/').filter(Boolean).slice(-1)[0]?.replaceAll('-',' ')||'overview';
 const navResults=useMemo(()=>{const q=search.trim().toLowerCase(); if(!q)return searchItems(user.role).slice(0,5); return searchItems(user.role).filter(([label])=>label.toLowerCase().includes(q)).slice(0,5)},[search,user.role]);
 const searchQ=useQuery({queryKey:['global-search',user.role,search.trim()],queryFn:()=>get<any>('/search',{q:search.trim(),role:user.role}),enabled:search.trim().length>=2,staleTime:10_000});
 const results=searchQ.data?.results?.length?searchQ.data.results:navResults;
 const goSearch=(path:string)=>{nav(path);setSearchOpen(false);setSearch('')};
 return <div className="min-h-screen bg-canvas">
  {open&&<button aria-label="Close navigation" className="fixed inset-0 z-40 bg-slate-950/25 lg:hidden" onClick={()=>setOpen(false)}/>}
  <aside className={`fixed inset-y-0 left-0 z-50 w-[272px] border-r border-line bg-white transition-transform duration-200 lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}>
   <div className="flex h-full flex-col">
    <div className="flex items-center justify-between p-5"><Logo/><button className="focus-ring rounded-lg p-2 text-muted lg:hidden" onClick={()=>setOpen(false)}><X size={18}/></button></div>
    <div className="mx-4 rounded-2xl border border-indigo-100 bg-indigo-50/70 p-3.5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-deep text-white"><UserRound size={18}/></div><div className="min-w-0"><p className="truncate text-sm font-bold">{user.name}</p><p className="mt-0.5 truncate text-xs capitalize text-muted">{user.role} · {user.department}</p></div></div></div>
    <nav className="scrollbar-thin mt-5 flex-1 space-y-1 overflow-y-auto px-3" aria-label={`${user.role} navigation`}>{items.map(([label,path,I])=><Link key={path} to={path} onClick={()=>setOpen(false)} className={`nav-item ${loc.pathname===path?'bg-indigo-50 text-brand':'text-muted hover:bg-slate-50 hover:text-ink'}`}><I size={18}/><span>{label}</span></Link>)}</nav>
    <div className="border-t border-line p-3"><button onClick={signOut} className="nav-item w-full text-muted hover:bg-red-50 hover:text-red-700"><LogOut size={18}/>Sign Out</button></div>
   </div>
  </aside>
  <main className="min-h-screen lg:pl-[272px]">
   <header className="sticky top-0 z-30 border-b border-line bg-white/90 backdrop-blur-xl"><div className="flex h-[72px] items-center gap-3 px-4 sm:px-6 lg:px-8"><button aria-label="Open navigation" className="focus-ring rounded-xl p-2.5 text-muted hover:bg-slate-100 lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div className="hidden lg:block shrink-0"><p className="text-xs font-medium capitalize text-quiet">Capacity Connect / {user.role}</p><p className="mt-0.5 text-sm font-bold capitalize">{title}</p></div><div className="relative ml-auto flex min-w-0 items-center gap-1.5">
     <div className="relative hidden sm:block"><div className={`flex h-10 w-[240px] items-center gap-2 rounded-xl border bg-slate-50 px-3 transition focus-within:border-brand focus-within:bg-white focus-within:ring-4 focus-within:ring-indigo-50 ${searchOpen?'border-brand':'border-transparent'}`}><Search size={17} className="shrink-0 text-quiet"/><input aria-label="Search Capacity Connect" value={search} onFocus={()=>setSearchOpen(true)} onChange={e=>{setSearch(e.target.value);setSearchOpen(true)}} onKeyDown={e=>{if(e.key==='Enter'&&results[0])goSearch(results[0][1])}} placeholder="Search" className="w-full bg-transparent text-sm outline-none placeholder:text-quiet"/></div>{searchOpen&&<><button aria-label="Close search" className="fixed inset-0 z-40 cursor-default" onClick={()=>setSearchOpen(false)}/><div className="absolute right-0 top-12 z-50 w-[300px] overflow-hidden rounded-2xl border border-line bg-white p-2 shadow-lift"><p className="px-3 py-2 text-[11px] font-bold uppercase tracking-[.16em] text-quiet">Search Capacity Connect</p>{searchQ.isFetching&&<p className="px-3 py-2 text-xs text-muted">Searching…</p>}{results.length?results.map((item:any)=>{const [label,path]=Array.isArray(item)?item:[item.label,item.path];return <button key={path} onClick={()=>goSearch(path)} className="flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-sm font-semibold hover:bg-slate-50"><span className="min-w-0 truncate">{label}</span><span className="ml-3 shrink-0 text-xs text-quiet">Open</span></button>}):!searchQ.isFetching&&<p className="px-3 py-3 text-sm text-muted">No matching result.</p>}</div></>}</div>
     <Link aria-label="Notifications" to={`/${user.role}/notifications`} className="focus-ring relative rounded-xl p-2.5 text-muted hover:bg-slate-100"><Bell size={18}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-brand"/></Link><div className="relative"><button aria-expanded={profileOpen} onClick={()=>setProfileOpen(x=>!x)} className="focus-ring ml-1 flex items-center gap-2 rounded-xl p-1.5 hover:bg-slate-100"><span className="grid h-9 w-9 place-items-center rounded-full bg-deep text-xs font-bold text-white">{user.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><ChevronDown size={15} className="hidden text-muted sm:block"/></button>{profileOpen&&<div className="absolute right-0 top-12 w-48 rounded-2xl border border-line bg-white p-2 shadow-lift"><Link className="block rounded-xl px-3 py-2 text-sm font-semibold hover:bg-slate-50" to={user.role==='trainee'?'/trainee/profile':user.role==='trainer'?'/trainer/profile':'/admin/profile'}>My profile</Link><Link className="block rounded-xl px-3 py-2 text-sm font-semibold hover:bg-slate-50" to={`/${user.role}/notifications`}>Notifications</Link><Link className="block rounded-xl px-3 py-2 text-sm font-semibold hover:bg-slate-50" to={`/${user.role}/settings`}>Settings</Link><button onClick={signOut} className="mt-1 w-full rounded-xl px-3 py-2 text-left text-sm font-semibold text-red-700 hover:bg-red-50">Sign out</button></div>}</div></div></div></header>
   <div className="mx-auto max-w-[1440px] p-4 sm:p-6 lg:p-8"><PageErrorBoundary>{children}</PageErrorBoundary></div>
  </main>
 </div>;
}
